[airtable]
api_key = "patE1JsBmEFvx7AQm.ab67bc167299d7a40d2ac7909dc491e880bf3123aa615abd76b5c5d857d72504"
base_id = "appWZr25oaxzCJrXZ"
table_id = "tblKKuT3VriuyHeqi"
table_24_id = "tblUudGTbW2y9mzaO"
base_24_id = "appi6rzeSzAiwou4K"
base_id_ld = "appEWQM8IUcJ2mzDx"
table_id_ld = "tblsUijyeFVJ1s8ma"

[fillout]
api_key = "sk_prod_qEZ3TQkoMxW4p5WGg0wfmfyfC1ucN94vkOG0P2mdHTMnRVRWPLJg0iherTh6udHSXrXSpBZSJmG6tbZrhaBYIj44NN2nCJnpdvx_26701"
form_id = "5WhpNbGHMdus"

[bitly]
access_token = "c7565305f122bae83811bbdc5b569a961c1dfd92"